### ISSUE TITLE
Microsoft AI Tour拝見し、試すもエラー

### ISSUE THREAD

**Issue by Ren-chongit** [geekfujiwara/OCR2GPT#1]
突然失礼します。Microsoft AI Tourで貴殿のセッションを拝見し、OCR2GPTに興味をもって試したものの「GPTする」をクリックするとエラーが発生します。

前提；
　1.アンマネージドソリューション
　2.地域間のデータ移動は有効化済み
　3.データ（画像）の読み込みやプロンプト（更新）は問題なし
　
エラー；
GPT でテキストを作成する.Predict が失敗しました: {"error":{"code":"0x80048d06","message":"{\"operationStatus\":\"Error\",\"error\":{\"type\":\"Error\",\"code\":\"ModelNotSupported\",\"message\":\"This scenario is not supported in this environment.\"},\"predictionId\":null}"}}

監視内容；
　・Network Predict エラー
　・応答ステータス：403
　・error > message: "This scenario is not supported in this environment."

365初心者のため基本的な間違いがあるかもですが、ご教授いただけると助かります。

**Comment by geekfujiwara** [comment]
ご興味をお持ちいただきありがとうございます。

AI Builder のアップデートにより、以前プレビューで提供されていた"GPT でテキストを作成する"というAIモデルは利用できなくなりました。

その対応としてformatGPTというAIプロンプトを作成してこちらのSolutionにアップデートしておりますのでご利用ください。
![image](https://github.com/geekfujiwara/OCR2GPT/assets/96101315/966bdf46-a87d-4de1-9dda-8271f03f12df)

こちらソリューションは定期的にアップデートしておりますのでこちらから最新版を入手ください。アンマネージドソリューションで運用されているということなので、競合を防ぐため各オブジェクトを削除した後にインポートしてみてください。
https://github.com/geekfujiwara/OCR2GPT/releases

簡易的にアップデートできるようにしたい場合はマネージドソリューションで管理されるのを推奨します。マネージドソリューションであればバージョン管理が行われバージョンの新しいもので上書きされます。
